sudo: false
dist: trusty
language: cpp
node_js:
  - "7"
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
before_install:
  - alias clang++="clang++-4.0"
install: npm install
script: ./configure.js && npm test
