os: linux
sudo: false
dist: trusty
language: generic
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - libc++-dev
env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9
install: npm install
script: ./configure.js && npm test
