os: linux
sudo: false
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - libc++-dev
env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9
install:
  - yarn install
script:
  - ./configure && yarn test
