os: linux
sudo: false
dist: trusty
language: generic
node_js:
  - "7"
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
env: COMPILER_NAME=clang CXX=clang++-4.0 CC=clang-4.0
install: npm install
script: $(CXX) --version && ./configure.js && npm test
