os: linux
sudo: false
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - libc++-dev
      - libstdc++6
env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9
install:
  - yarn install
script:
  - node_modules/.bin/babel-node --plugins transform-flow-strip-types configure.js && yarn test
