#pragma once

#include <vector>
#include <string>
#include <thread>
#include <unordered_set>
#include <unordered_map>
#include <fcntl.h>
#include <future>
#include <iostream>
#include <spawn.h>
#include <sstream>
#include <stdexcept>
#include <stdlib.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <condition_variable>
#include <memory>
#include <mutex>
#include <queue>
#include <stack>
